### ISSUE TITLE
"吴"没有tūn的音

### ISSUE THREAD

**Issue by suyi91** [mozillazg/pinyin-data#18]
[吴 （汉语汉字）](https://baike.baidu.com/item/%E5%90%B4/1558#viewPageContent)

**Comment by mozillazg** [comment]
感谢反馈。看了一下，有些字典上有这个音：

《汉语大字典》上有这个音：http://www.guoxuedashi.com/kangxi/pic.php?f=dzd&p=634
 Unihan 上也有：https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=%E5%90%B4

待我找找最新版的实体书确认一下。

**Comment by twang2218** [comment]
有这个读音，在《汉语大字典.第二版》中，633-634页，第三个解释：tūn 《俗字背篇》吐根切。同“吞”。

<img width="626" alt="截屏2020-11-05 12 27 24 - 庄" src="https://user-images.githubusercontent.com/6299096/98186693-6e702a00-1f63-11eb-8c69-598e290d7538.png">
