### ISSUE TITLE
对应的拼音看不到文字

### ISSUE THREAD

**Issue by Samurais** [mozillazg/pinyin-data#23]
下载后查看 pinyin.txt
https://github.com/mozillazg/pinyin-data/raw/edb08de465dcb3fb92bcc609c8b52db535e36bea/pinyin.txt

有些行看起来如下：
![image](https://user-images.githubusercontent.com/3538629/38082593-b7f90d00-3379-11e8-9a7f-956014409efd.png)

其有unicode,  但是  文字却显示不出来。

**Comment by mozillazg** [comment]
@Samurais 正常，因为那些汉字大部分字体都显示不了。

比如最后的 `U+2A533` 是这样的（图片来自：http://www.guoxuedashi.com/zidian/z70078f.html ）：

![default](https://user-images.githubusercontent.com/485054/38086380-af99f3ba-3386-11e8-8d99-51efff622d8a.png)

**Comment by andyhu** [comment]
是字体的问题。你下个方正超大字库看看
