### ISSUE TITLE
"庄"多了peng的音

### ISSUE THREAD

**Issue by hunshcn** [mozillazg/pinyin-data#30]
应该只有zhuang的音，peng在各处都找不到

**Comment by mozillazg** [comment]
@chunsh peng 这个是旧读音，似乎是可以去掉：

http://www.guoxuedashi.com/kangxi/pic.php?f=dzd&p=936
<img width="475" alt="image" src="https://user-images.githubusercontent.com/485054/50544933-48c7ba80-0c40-11e9-8664-fa1555a9d5c5.png">

**Comment by twang2218** [comment]
《汉语大字典.第二版》936页：
<img width="590" alt="截屏2020-11-05 12 23 41" src="https://user-images.githubusercontent.com/6299096/98185920-c1e17880-1f61-11eb-9ee2-98d9a4c83c4d.png">
