### ISSUE TITLE
支持日本自造汉字

### ISSUE THREAD

**Issue by mozillazg** [mozillazg/pinyin-data#32]
详见：https://github.com/mozillazg/rust-pinyin/issues/30

**Comment by LuoZijun** [comment]
数据来源: 

* [日本汉字的汉语读音规范](http://www.moe.gov.cn/s78/A19/yxs_left/moe_810/s230/201001/t20100115_75698.html)
* [日本汉字的汉语普通话规范读音表- 维基百科](https://zh.wikipedia.org/wiki/%E6%97%A5%E6%9C%AC%E6%B1%89%E5%AD%97#7_%E6%97%A5%E6%9C%AC%E6%B1%89%E5%AD%97%E7%9A%84%E6%B1%89%E8%AF%AD%E6%99%AE%E9%80%9A%E8%AF%9D%E8%A7%84%E8%8C%83%E8%AF%BB%E9%9F%B3%E8%A1%A8)

数据条目（总计32条）:

```
U+5302: yún # 匂
U+4e3c: dǎn # 丼
U+8fbb: shí # 辻
U+8fbc: rù # 込
U+51e7: jīn # 凧
U+6763: shān # 杣
U+67a0: zá # 枠
U+7551: tián # 畑
U+6803: lì # 栃
U+6802: méi # 栂
U+5ce0: kǎ # 峠
U+4fe3: yǔ # 俣
U+7c7e: rèn # 籾
U+7560: tián # 畠
U+96eb: xià # 雫
U+7b39: shì # 笹
U+5840: píng # 塀
U+6919: chāng # 椙
U+7872: yù # 硲
U+86ef: lǎo # 蛯
U+55b0: cān # 喰
U+643e: zhà # 搾
U+698a: shén # 榊
U+50cd: dòng # 働
U+7cc0: huā # 糀
U+9786: bǐng # 鞆
U+69c7: zhēn # 槇
U+6a2b: jīan # 樫
U+9d2b: tián # 鴫
U+567a: xīn # 噺
U+7c17: liáng # 簗
U+9ebf: mó # 麿
```

**Comment by LuoZijun** [comment]
PR: #33

**Comment by LuoZijun** [comment]
@mozillazg 这个看起来可以关闭了 :)
