### ISSUE TITLE
"嗯"字的拼音错误

### ISSUE THREAD

**Issue by Tairycy** [mozillazg/pinyin-data#36]
from pypinyin import pinyin, Style
p = pinyin("嗯", style=Style.TONE3)
print(p)

结果为 [['n2']]

**Comment by mozillazg** [comment]
拼音没错，详情请参考 https://github.com/mozillazg/python-pinyin/issues/109 这个问题。

**Comment by Tairycy** [comment]
受教了，谢谢！
