### ISSUE TITLE
'怀'字多了一个拼音'fu'

### ISSUE THREAD

**Issue by HENScience** [mozillazg/pinyin-data#38]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Ubuntu 18.04.3 LTS
* Python 版本： 3.6.8
* pypinyin 版本：pypinyin-0.36.0

## 问题描述
‘怀'字pypinyin的结果为：[['huai', 'fu']]

## 问题复现步骤
pinyin('怀', style=Style.NORMAL, heteronym=True, errors='ignore')
Out[77]: [['huai', 'fu']]

**Comment by mozillazg** [comment]
感谢反馈。unihan 中有 fu 这个读音：https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=%E6%80%80 ，等我有空的时候确认一下是不是需要删除这个拼音。

**Comment by HENScience** [comment]
不客气，我这边只用到了中文简体的拼音，日韩越没有关注，谢谢

**Comment by twang2218** [comment]
应该没有错误，在《汉语大字典.第二版》中，2436页中，“怀”字的解释是：
<img width="586" alt="截屏2020-11-05 12 14 23" src="https://user-images.githubusercontent.com/6299096/98185590-06b8df80-1f61-11eb-8e38-5ec6a70ac375.png">
fù 《俗字背篇》音副，怒也。
