### ISSUE TITLE
在（GBK/GB 18030）PUA 映射的注释中提及实际 Unihan 码位，并酌情重命名文件

### ISSUE THREAD

**Issue by Artoria2e5** [mozillazg/pinyin-data#7]
想要再确认一次映射表的话可以参考 https://zh.wikipedia.org/wiki/GB_18030#PUA 。其实是可以用表配合脚本生成 PUA 数据文件的……

强调 GB PUA 的原因是因为 Big5-HKSCS。

**Comment by mozillazg** [comment]
@Artoria2e5 好的，我看看。Thanks!
